### ISSUE TITLE
Broken link, Intro to Ruby iterators

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/intro-to-ruby-iterators#22]
On Intro to Ruby Iterators, 

This link doesn't work: RESOURCES
.each on Codecademy

**Comment by curiositypaths** [comment]
Hi There,

Thank you for notifying us. We removed the broken link.

As always, thank you for contributing. 💙

**Comment by MiriamPeskowitz** [comment]
💙 Anytime!
