### ISSUE TITLE
Broken Link: link to Codecademy generates 404 error

### ISSUE THREAD

**Issue by jaf7** [learn-co-curriculum/intro-to-ruby-iterators#23]
The link to Codecademy at the bottom of the page generates a 404 Not Found Error.
There doesn't appear to be a correct link to obtain trivially because the lesson page is behind a login/signup mechanism.

**Link:**
```HTML
<a href="https://www.codecademy.com/en/courses/ruby-beginner-en-XYcN1/2/4?curriculum_id=5059f8619189a5000201fbcb" target="_blank"><code>.each</code> on Codecademy</a>
```

**Comment by curiositypaths** [comment]
Hi There,

Thank you for notifying us. We removed the broken link.

As always, thank you for contributing. 💙
