### ISSUE TITLE
Broken link 404 error

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/intro-to-ruby-iterators#24]
The following link at the bottom of this lesson is broken.

".each on Codecademy"

https://www.codecademy.com/en/courses/ruby-beginner-en-XYcN1/2/4?curriculum_id=5059f8619189a5000201fbcb

**Comment by curiositypaths** [comment]
Hi There,

Thank you for notifying us. We removed the broken link.

As always, thank you for contributing. 💙
