### ISSUE TITLE
The Resources section has no resources.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/intro-to-ruby-iterators#27]
At the very bottom of this lesson, there is a **Resources** section, but there are no resources listed. Thanks for looking into this!

Sdcrouse

**Comment by cjbrock** [comment]
Well that's pretty useless! I went ahead and removed it. We have a general scaffold for our lessons, but we don't always use them (sometimes we don't always have resources that are necessary, or sometimes they can be overwhelming at certain points). Thanks @Sdcrouse.

// <3 Corinna

**Comment by Sdcrouse** [comment]
You're quite welcome, @cjbrock! Happy to help!
